name: Build and Deploy to Render

on:
  push:
    branches:
      - main  # or your main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js 22
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      - name: Build frontend
        run: |
          cd frontend
          npm run build

      - name: Install backend dependencies
        run: npm install

      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          # Get your Render service ID from your Render dashboard
          SERVICE_ID="your-render-service-id"

          curl -X POST "https://api.render.com/deploy/srv-${SERVICE_ID}" \
            -H "Accept: application/json" \
            -H "Authorization: Bearer $RENDER_API_KEY"
